### ISSUE TITLE
rake build fails when gem isn't installed

### ISSUE THREAD

**Issue by eedwards-sk** [poise/halite#12]
I'm working out of a halite gem `my_org-example_cookbook` and attempting to use `rake build` from the gem's source directory

It appears that it's attempting to get the spec for the gem from the local gem repo rather than the gemspec that's present in the current folder.

```
→ rake build
rake aborted!
Halite::Error: Cannot find a gem to satisfy my_org-example_cookbook (>= 0): Gem::MissingSpecError
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/gem.rb:268:in `rescue in dependency_to_spec'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/gem.rb:264:in `dependency_to_spec'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/gem.rb:63:in `spec'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/gem.rb:58:in `initialize'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite.rb:43:in `new'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite.rb:43:in `convert'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/rake_helper.rb:127:in `build_cookbook'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/rake_helper.rb:43:in `block in install'

Caused by:
Gem::MissingSpecError: Could not find 'my_org-example_cookbook' (>= 0) among 269 total gem(s)
Checked in 'GEM_PATH=/Users/username/.chefdk/gem/ruby/2.4.0:/opt/chefdk/embedded/lib/ruby/gems/2.4.0', execute `gem env` for more information
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/gem.rb:264:in `dependency_to_spec'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/gem.rb:63:in `spec'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/gem.rb:58:in `initialize'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite.rb:43:in `new'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite.rb:43:in `convert'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/rake_helper.rb:127:in `build_cookbook'
/Users/username/.chefdk/gem/ruby/2.4.0/gems/halite-1.8.0/lib/halite/rake_helper.rb:43:in `block in install'
Tasks: TOP => build => chef:build
(See full trace by running task with --trace)
```

when if I run a `bundle info my_org-example_cookbook` you can see that it's resolved

```
→ bundle info my_org-example_cookbook
Resolving dependencies...
  * my_org-example_cookbook (0.0.0)
	Summary: example cookbook
	Homepage: https://github.com/my_org/example-cookbook
	Path: /Users/username/Documents/dev/local/example-cookbook
```

Should I have to install the gem I'm working on into the local gem repository just to build the cookbook for it?

**Comment by coderanger** [comment]
You probably need to be doing `bundle exec rake build` if you don't have a shell helper to automatically add `bundle exec` to things. Or use a bundler binstub, same effect.

**Comment by eedwards-sk** [comment]
@coderanger oh awesome, what a simple solution, thanks again, Noah!
