### ISSUE TITLE
Halite fails to initialize with Berkshelf 6.1+

### ISSUE THREAD

**Issue by gdavison** [poise/halite#9]
The `initialize` function for `::Berkshelf::Source` now takes 2 parameters, but `Halite::Berkshelf::Source` only passes 1.

Locking the Berkshelf gem to `~> 6.0` is useable as a workaround.

The resulting error is:
```
ArgumentError:
  wrong number of arguments (given 1, expected 2)
# .../gems/halite-1.7.0/lib/halite/berkshelf/source.rb:33:in `initialize'
# .../gems/halite-1.7.0/lib/halite/berkshelf/helper.rb:52:in `new'
# .../gems/halite-1.7.0/lib/halite/berkshelf/helper.rb:52:in `block (2 levels) in install'
```

**Comment by coderanger** [comment]
Oh right, I changed that API.
